# Generated by Django 6.0.1 on 2026-01-20 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Тип документа')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('completed', 'Выполнен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Одобрил')),
                ('completed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_documents', to='documents.document', verbose_name='Созданный документ')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Запрос документа',
                'verbose_name_plural': 'Запросы документов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('document_type', models.CharField(choices=[('order', 'Приказ'), ('contract', 'Договор'), ('act', 'Акт'), ('memo', 'Служебная записка'), ('letter', 'Письмо'), ('report', 'Отчет'), ('application', 'Заявление'), ('other', 'Другое')], max_length=50, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content_template', models.TextField(blank=True, verbose_name='Шаблон содержимого')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Количество использований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quick_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Быстрый шаблон',
                'verbose_name_plural': 'Быстрые шаблоны',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('delegated', 'Делегировано')], default='pending', max_length=20, verbose_name='Решение')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Утверждающий')),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Делегировано')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.workflowstep', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Одобрение',
                'verbose_name_plural': 'Одобрения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('documents_created', models.IntegerField(default=0, verbose_name='Создано документов')),
                ('documents_approved', models.IntegerField(default=0, verbose_name='Одобрено документов')),
                ('documents_rejected', models.IntegerField(default=0, verbose_name='Отклонено документов')),
                ('avg_approval_time', models.FloatField(default=0, verbose_name='Среднее время одобрения (часы)')),
                ('team_members_count', models.IntegerField(default=0, verbose_name='Количество членов команды')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Статистика команды',
                'verbose_name_plural': 'Статистика команд',
                'ordering': ['-date'],
                'unique_together': {('manager', 'date')},
            },
        ),
    ]
