# Generated by Django 6.0.1 on 2026-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentrequest_quicktemplate_workflowapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='generated_file',
            field=models.FileField(blank=True, help_text='Автоматически сгенерированный файл из шаблона', null=True, upload_to='generated/%Y/%m/', verbose_name='Сгенерированный файл'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='file_format',
            field=models.CharField(choices=[('docx', 'Word документ (.docx)'), ('xlsx', 'Excel таблица (.xlsx)'), ('pptx', 'PowerPoint презентация (.pptx)'), ('pdf', 'PDF документ (.pdf)'), ('html', 'HTML документ (.html)')], default='docx', max_length=10, verbose_name='Формат файла'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, help_text='Словарь с описанием доступных плейсхолдеров', verbose_name='Плейсхолдеры'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='Загрузите файл шаблона с плейсхолдерами {{переменная}}', null=True, upload_to='templates/%Y/%m/', verbose_name='Файл шаблона'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='html_template',
            field=models.TextField(blank=True, help_text='Используйте {{placeholder}} для переменных', verbose_name='HTML шаблон'),
        ),
    ]
