# Generated by Django 6.0.1 on 2026-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_generated_file_documenttemplate_file_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='placeholders',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='html_template',
            field=models.TextField(blank=True, help_text='Используйте {{placeholder}} для переменных (только для HTML)', verbose_name='HTML шаблон'),
        ),
    ]
