# Generated by Django 6.0.1 on 2026-02-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_documenttemplate_placeholders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='registry_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Регистрационный номер'),
        ),
    ]
