# Generated by Django 6.0.1 on 2026-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_approval_type_document_is_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text='Список плейсхолдеров для заполнения: [{"name": "company_name", "label": "Название компании", "type": "text", "required": true}]', verbose_name='Плейсхолдеры'),
        ),
    ]
