# Generated by Django 6.0.1 on 2026-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_placeholders_to_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='file_format',
            field=models.CharField(choices=[('docx', 'Word документ (.docx)'), ('xlsx', 'Excel таблица (.xlsx)'), ('pdf', 'PDF документ (.pdf)')], default='docx', max_length=10, verbose_name='Формат файла'),
        ),
        migrations.DeleteModel(
            name='DocumentRequest',
        ),
    ]
